# Generated by Django 3.2.19 on 2023-06-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_type', models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], max_length=15)),
            ],
        ),
    ]
