# Generated by Django 3.2.19 on 2023-06-14 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0003_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_type',
            name='member_type',
            field=models.CharField(choices=[('Student member', 'Student member(0 and ongoing student)'), ('Affiliate member', 'Affiliate member(graduated and 0 years)'), ('Associate member', 'Associate memeber(1-2 years)'), ('Full member', 'Full member(3 years)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='member_type',
            name='years_trained',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='Applicant_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('identification_card', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
                ('organization_name', models.CharField(max_length=50)),
                ('organization_address', models.TextField(max_length=100)),
                ('organization_telephone', models.CharField(max_length=30)),
                ('business_email', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
