# Generated by Django 3.2.19 on 2023-06-14 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0004_auto_20230614_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_institution', models.CharField(max_length=50)),
                ('date_from', models.DateTimeField(max_length=30)),
                ('date_to', models.DateTimeField(max_length=30)),
                ('certificate_awarded', models.CharField(max_length=30)),
                ('certificate_file', models.FileField(upload_to='documents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
