# Generated by Django 3.2.19 on 2023-06-15 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0005_academic_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialized_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trainer', models.BooleanField(default=False)),
                ('Auditor', models.BooleanField(default=False)),
                ('Assesor', models.BooleanField(default=False)),
                ('Implementor', models.BooleanField(default=False)),
                ('Management_representative', models.BooleanField(default=False)),
                ('Process_owner', models.BooleanField(default=False)),
                ('Member_of_quality_improvement_team', models.BooleanField(default=False)),
                ('Quality_assurance_manager', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
