# Generated by Django 3.2.19 on 2023-06-15 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0007_information_on_present_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Length_of_tenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_organization', models.CharField(max_length=30)),
                ('date_from', models.DateField(max_length=30)),
                ('date_to', models.DateField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
