# Generated by Django 3.2.19 on 2023-06-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_auto_20230620_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_details',
            name='tittle',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Prof', 'Prof'), ('Miss', 'Miss')], max_length=10, null=True),
        ),
    ]
