# Generated by Django 3.2.19 on 2023-06-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_applicant_details_tittle'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_qualification',
            name='course_duration_in_years',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4, null=True),
        ),
    ]
