# Generated by Django 3.2.19 on 2023-07-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0025_remove_membership_officer_membership_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership_officer',
            name='Member',
        ),
    ]
