# Generated by Django 3.2.19 on 2023-07-26 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membership', '0027_auto_20230710_0742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership_officer',
            new_name='Membership_applications',
        ),
    ]
